# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tests/app/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

from PyQt5.QtWidgets import QLabel

from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.pixmap = QPixmap('..\image.png')
        self.pixmap = self.pixmap.scaled(800, 600, aspectRatioMode=Qt.KeepAspectRatio)
        self.image_label = QLabel(self)
        self.image_label.setPixmap(self.pixmap)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.auto_number = QtWidgets.QLineEdit(self.widget)
        self.auto_number.setObjectName("auto_number")
        self.verticalLayout_2.addWidget(self.auto_number)
        self.send = QtWidgets.QPushButton(self.widget)
        self.send.setObjectName("send")
        self.send.setStyleSheet("background-color: white;")
        self.verticalLayout_2.addWidget(self.send)
        self.verticalLayout_2.addWidget(self.image_label)
        self.answer = QtWidgets.QTextBrowser(self.widget)
        self.answer.setObjectName("answer")
        self.verticalLayout_2.addWidget(self.answer)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.image_label
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send.setText(_translate("MainWindow", "Получить уведомление"))
